services:
  backend:
    image: registry.cloudbility.com.cn/charmirror/multi-app/backend:r20260604.2
    container_name: md2word-backend
    env_file:
      - .env
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    image: registry.cloudbility.com.cn/charmirror/multi-app/frontend:r20260604.2
    container_name: md2word-frontend
    depends_on:
      - backend
    ports:
      - "3002:80"
    restart: unless-stopped
