services:
  md2word-web:
    image: registry.cloudbility.com.cn/charmirror/md2word/md2word-web:r20260429
    container_name: md2word-web
    ports:
      - "3002:8000"
    environment:
      DOCX_TEMPLATE_PATH: /app/assets/reference.docx
    restart: unless-stopped
